var quotes = [
    ["Stay positive and don’t die.", "William 'Drated Cuz' Broyles"],
    ["Stay positive and don’t die.", "Jeff Cannata"],
    ["Stay tight." - "Jimmy 'DJ Tyrant' Blocksom"],
    ["6.5 out of 10", "IGN"],
    ["When I watch Rich play, I tell myself, 'Okay, so he practiced that. One hour of practice and I could do that'.", "Taylor 'Arthelon' Eder"],
    ["Lagf", "Christopher 'Zuna' Buechter"],
    ["                                                         323", "Jiwoom 'Miwa' Yang"],
    ["You guys do know Nova is the best player killer in the game. A good Nova can beat anyone.", "Jaehyung 'chu8' Park"],
    ["Indeed.", "Jaycie 'Gillyweed' Gluck"],
    ["Oooooooaaaaaaaaahhhhh!", "Jaycie 'Gillyweed' Gluck"],
    ["Report Abathur AFK", "Half of the players in Alpha"],
    ["No comeback mechanics.", "IGN"],
    ["Focus Morales!", "At least one person on every team to ever face Lt. Morales"],
    ["Typical NA. Big mouths, small arms.", "Thomas 'Mene' Cailleux"],
    ["Worth", "The guy who just over extended and died."],
    ["Are you Bronze League?", "D.Va"],
    ["Hey! I got an idea: How about you go 30 yards that away and stand real still?", "Sgt. Hammer"],
    ["No man can defeat me. Although, 10 to 25 might do the trick.", "Arthas"],
    ["If I had a face, I’d be glaring at you, right now.", "Tyrael"],
    ["Conversation superfluous. Focus upon combat.", "Abathur"],
    ["Pronouns. Unclear.", "Abathur"],
    ["Logical decision.", "Abathur"],
    ["Is this the best healing you can do?", "Alarak"],
    ["You're not good at this, are you?", "Alarak"],
    ["Have you come seeking wisdom? You certainly need it.", "Alarak"],
    ["Free-to-Play is a delusion granted to the weak by the strong. Or so I've heard.", "Alarak"],
    ["Wow!", "Cattleprod"],
    ["*$@#s free!", "Christopher 'Zuna' Buechter"],
    ["*$@#s free!", "Mike 'Glaurung' Fisk"],
    ["Sometimes in life you lose, and sometimes you face NA.", "Simon 'scHwimpi' Svensson"],
]